---
- stat: path=/tmp/bootstrapped
  register: bootstrapped
  tags: bootstrap

- include: bootstrap.yml
  when: bootstrapped.stat.exists == false or bootstrapped.stat.isreg == false

- shell: locale-gen de_DE.UTF-8
  sudo: true

- shell: dpkg-reconfigure locales
  sudo: true

- apt: pkg={{ item }} state=latest
  sudo: true
  with_items:
    # utilities
    - htop
    - vim
    - git
    - wget
    - curl
    - multitail
    # python dependencies
    - python-pip
    - python-dev
    - python-virtualenv
