---
- name: install required packages
  apt: pkg={{ item }} state=latest
  sudo: true
  with_items:
    - supervisor
    # thumbor dependencies
    - libcurl4-gnutls-dev
    - gifsicle
    # opencv
    - build-essential
    - libavformat-dev
    - x264
    - v4l-utils
    - ffmpeg
    - libcv2.3
    - libcvaux2.3
    - libhighgui2.3
    - python-opencv
    - opencv-doc
    - libcv-dev
    - libcvaux-dev
    - libhighgui-dev
  tags: thumbor

- name: create thumbor virtualenv
  shell: virtualenv "/home/{{ ansible_ssh_user }}/.virtualenvs/thumbor" creates="/home/{{ ansible_ssh_user }}/.virtualenvs/thumbor/bin/activate"
  tags: thumbor

- name: copy thumbor requirements.txt into virtualenv
  copy: src=requirements.txt dest=/home/{{ ansible_ssh_user }}/.virtualenvs/thumbor/requirements.txt
        owner=root group=root mode=755
  tags: thumbor
  sudo: true

- name: install thumbor pips
  pip: requirements=/home/{{ ansible_ssh_user }}/.virtualenvs/thumbor/requirements.txt
       virtualenv=/home/{{ ansible_ssh_user }}/.virtualenvs/thumbor
  tags: thumbor

- name: create thumbor.conf
  template: src=thumbor.conf.j2 dest=/etc/thumbor.conf owner=root group=root mode=755
  sudo: true
  tags: thumbor

- name: copy the opencv so-file to virtualenv
  shell: cp -f /usr/lib/pyshared/python2.7/cv* /home/{{ ansible_ssh_user }}/.virtualenvs/thumbor/lib/python2.7/site-packages/
  tags: thumbor

- name: copy thumbor config for supervisorctl
  template: src=supervisor.conf.j2 dest=/etc/supervisor/conf.d/thumbor.conf owner=root group=root mode=755
  sudo: true
  tags: thumbor

- name: restart thumbor
  supervisorctl: name="thumbor:" state=restarted
  sudo: true
  tags: thumbor
