---
- apt: name='{{ item }}'
  with_items:
    - libpq-dev
    - python-dev
    - postgresql
    - postgresql-contrib
    - python-psycopg2
  sudo: true


- postgresql_user: user='{{ app.id }}' password='{{ app.id }}' role_attr_flags=CREATEDB,NOSUPERUSER
  sudo: true
  sudo_user: postgres


# Create a new database
- postgresql_db: name='{{ app.id }}' owner='{{ app.id }}'
  sudo: true
  sudo_user: postgres


- service: name=postgresql state=reloaded
  sudo: true