---
user:
  name: deploy
  home: /home/deploy

app:
  name: "Feinschmecker image upload form"
  id: "feinschmecker_image_upload_form"
  version: master
  domain: "upload.der-feinschmecker-shop.de"
  basedir: "{{ user.home }}/feinschmecker_image_upload_form"
  media_path: "{{ user.home }}/feinschmecker_image_upload_form/.media"
  static_path: "{{ user.home }}/feinschmecker_image_upload_form/.static"
  environment: production # development | production | staging | testing
  webserver_port: 80