---
user:
  name: deploy
  home: /home/deploy

project:
  name: "Trendsetter"
  id: "trendsetter_production"

app:
  version: master
  domain: "upload.der-feinschmecker-shop.de"
  basedir: "{{ user.home }}/{{ project.id }}"
  media_path: "{{ user.home }}/{{ project.id }}/.media"
  static_path: "{{ user.home }}/{{ project.id }}/.static"
  environment: production # development | production | staging | testing
  webserver_port: 80