---
user:
  name: deploy
  home: /home/deploy

project: &PROJECT
  name: "Trendsetter"
  id: "trendsetter_staging"

app:
  <<: *PROJECT
  repo: git@bitbucket.org:intosite/trendsetter-django.git
  version: develop
  domain: "staging.django.trendsetter.eu"
  basedir: "{{ user.home }}/{{ project.id }}"
  media_path: "{{ user.home }}/{{ project.id }}/.media"
  static_path: "{{ user.home }}/{{ project.id }}/.static"
  environment: staging # development | production | staging | testing
  webserver_port: 8080