---
user:
  name: vagrant
  home: /home/vagrant

project: &PROJECT
  name: "product-test"               # just for identity ;)
  id: "product-test"                 # will be used for config and log files as well as the project folder

app:
  <<: *PROJECT
  repo: git@bitbucket.org:intosite/product-test-django.git
  version: develop                  # represents the repository version, this can be a branch a version hash or tag
  basedir: "/vagrant"               # the base path of your project
  media_path: "/vagrant/.media"     # the media path of your project
  static_path: "/vagrant/.static"   # the folder where you host your static files
  environment: development          # development | production | staging | testing
  domain: "product-test.local"       # domain name of the webserver configuration
  webserver_port: 80
  uwsgi_socket: "127.0.0.1:3031"