- name: add newrelic repo
  apt_repository: repo="deb http://apt.newrelic.com/debian/ newrelic non-free" state=present
  sudo: true

- name: trust new relic repo key
  shell: wget -O /tmp/newrelic.gpg https://download.newrelic.com/548C16BF.gpg; apt-key add /tmp/newrelic.gpg
  sudo: true

- name: install newrelic-sysmond
  apt: pkg=newrelic-sysmond state=latest update_cache=yes cache_valid_time=600 force=yes
  sudo: true

- name: configure newrelic
  shell: nrsysmond-config --set license_key={{ newrelic_license_key }}
  sudo: true
  when: newrelic_license_key is defined

- name: start newrelic-sysmond
  service: name=newrelic-sysmond state=started
  sudo: true
  when: newrelic_license_key is defined