

- name: disable default vhost
  action: file path=/etc/nginx/conf.d/example_ssl.conf state=absent
  sudo: true
  tags: nginx
  notify:
    - reload nginx

- name: deploy nginx configuration
  action: template src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  sudo: true
  tags: nginx
  notify:
    - reload nginx

- name: deploy app configuration
  action: template src=conf.j2 dest=/etc/nginx/conf.d/{{ app.name }}.conf
  sudo: true
  tags: nginx
  notify:
    - reload nginx
