---
- apt: name=nginx
  sudo: true

- name: delete default vhost
  file: name=/etc/nginx/sites-available/default state=absent
  sudo: true
  tags: bootstrap

- template: src=virtual_host.j2 dest=/etc/nginx/sites-enabled/site owner=www-data group=www-data mode=0644
  sudo: true

- name: reload nginx
  service: name=nginx state=reloaded
  sudo: true
  tags: bootstrap