- name: install nginx package
  apt: pkg={{ item }} state=present
  sudo: true
  with_items:
    - nginx=1.7.0-1~wheezy
  tags: nginx
  when: ansible_distribution == 'Debian'

- name: add nginx repo
  apt_repository: repo='deb http://nginx.org/packages/mainline/debian/ wheezy nginx' state=present update_cache=yes
  sudo: true
  tags: nginx
  when: ansible_distribution == 'Ubuntu'

- name: install nginx package
  apt: pkg=nginx state=latest force=YES
  sudo: true

- name: disable default vhost
  action: file path=/etc/nginx/conf.d/default.conf state=absent
  sudo: true
  tags: nginx
  notify:
    - reload nginx

- name: disable default vhost
  action: file path=/etc/nginx/conf.d/example_ssl.conf state=absent
  sudo: true
  tags: nginx
  notify:
    - reload nginx

- name: deploy nginx configuration
  action: template src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  sudo: true
  tags: nginx
  notify:
    - reload nginx

- name: deploy app configuration for production
  action: template src=production.conf.j2 dest=/etc/nginx/conf.d/{{ app.name }}.conf
  sudo: true
  tags: [nginx, production]
  notify:
    - reload nginx

- name: deploy app configuration for staging
  action: template src=staging.conf.j2 dest=/etc/nginx/conf.d/{{ app.name }}-staging.conf
  sudo: true
  tags: [nginx, staging]
  notify:
    - reload nginx
