---
- apt_repository: repo='ppa:chris-lea/uwsgi' update_cache=yes validate_certs=no
  sudo: true

- apt: name={{ item }} state=latest
  sudo: true
  with_items:
    - uwsgi
    - uwsgi-plugin-python

# creates an upstart conf which makes use of the uwsgi emporer mode
- template: src=upstart.uwsgi.conf
            dest=/etc/init/uwsgi.conf
  sudo: true

- template: src=site_uwsgi.ini.j2
            dest=/etc/uwsgi/apps-enabled/{{ app.id }}.ini
            owner=www-data
            group=www-data
            mode=0644
  sudo: true

#- template: src=default.j2 dest=/etc/default/uwsgi owner=root group=root mode=0644
#  sudo: true

- service: name=uwsgi state=restarted
  sudo: true